name: Validación de archivos

on:
  push:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Validar archivos requeridos
        run: |
          test -f index.html
          test -d css
          test -d js
          test -d partials
          test -d img
          test -f eventos.html
          test -f inforDinos.html
          test -f sectionNoticias.html
